export enum SectorEnum {
    HEALTHCARE = 'Healthcare',
    INDUSTRIALS = 'Industrials',
    TECHNOLOGY = 'Technology',
    CONSUMER_DEFENSIVE = 'Consumer Defensive',
    BASIC_MATERIALS = 'Basic Materials',
    COMMUNICATION_SERVICES = 'Communication Services',
    CONGLOMERATES = 'Conglomerates',
    CONSUMER_CYCLICAL = 'Consumer Cyclical',
    CONSUMER_GOODS = 'Consumer Goods',
    ENERGY = 'Energy',
    FINANCIAL = 'Financial',
    FINANCIAL_SERVICES = 'Financial Services',
    INDUSTRIALS_GOODS = 'Industrial Goods',
    OTHER = 'Other',
    REAL_ESTATE = 'Real Estate',
    SERVICES = 'Services',
    UTILITIES = 'Utilities',
}